title: "Rishabh Singhal Academic Website"
description: "PhD Student in Neuroengineering"
theme: minima
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
profile_image: "/assets/images/main.jpg"
linkedin_username: https://www.linkedin.com/in/rishabh-singhal-8124451b8/
#--------------------------------------------------------------------------------
timeline_events:
  - date: "2018"
    content: "Started my PhD at McGill University, focusing on neuroengineering projects."
  - date: "2021"
    content: "Published my first paper on modeling cognition with recurrent neural networks."
  - date: "2023"
    content: "Presented my research at an international neuroscience conference."
